version: '3.4'

services:
  tanuljunk:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  cats:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dogs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
