version: '3.4'

services:
  tanuljunk:
    image: ${DOCKER_REGISTRY-}tanuljunk
    build:
      context: .
      dockerfile: Tanuljunk/Dockerfile
    depends_on:
        - sql
    expose:
        - 80
    restart: always
    container_name: tanuljunk
    hostname: tanuljunk
    domainname: tanuljunk
  
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    expose:
        - 1433
    environment:
        - ACCEPT_EULA=y
        - SA_PASSWORD=A&VeryComplex123Password
  
  postgresql:
    image: "postgres:latest"
    container_name: postgresql
    environment:
        - POSTGRES_PASSWORD=A&VeryComplex123Password
    expose:
        - 5432
    restart: always
  
  mysql: 
    image: "mysql:latest"
    container_name: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=A&VeryComplex123Password
    expose:
        - 3306
    restart: always

  cats:
    image: ${DOCKER_REGISTRY-}cats
    build:
      context: .
      dockerfile: Cats/Dockerfile
    depends_on:
        - mysql
    expose:
        - 80
    restart: always
    container_name: cats
    hostname: cats
    domainname: cats

  dogs:
    image: ${DOCKER_REGISTRY-}dogs
    build:
      context: .
      dockerfile: Dogs/Dockerfile
    depends_on:
        - postgresql
    expose:
        - 80
    restart: always
    container_name: dogs
    hostname: dogs
    domainname: dogs
  
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
        - "55520:80"
    restart: always 
    depends_on:
        - cats
        - dogs
        - tanuljunk
    container_name: gateway
    hostname: gateway
    domainname: gateway

