version: '3.4'

services:
  tanuljunk:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  cats:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dogs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
