version: '3.4'

services:
  tanuljunk:
    image: ${DOCKER_REGISTRY-}tanuljunk
    build:
      context: .
      dockerfile: Tanuljunk/Dockerfile
    depends_on:
        - sql
    ports:
        - "55522:80"
    restart: always
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
        - "1433:1433" 
    environment:
        - ACCEPT_EULA=y
        - SA_PASSWORD=A&VeryComplex123Password
  postgresql:
    image: "postgres:latest"
    container_name: postgresql
    environment:
        - POSTGRES_PASSWORD=A&VeryComplex123Password
    ports:
        - "5432:5432" 
    restart: always
  
  mysql: 
    image: "mysql:latest"
    container_name: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=A&VeryComplex123Password
    ports:
        - "3306:3306"   
    restart: always

  cats:
    image: ${DOCKER_REGISTRY-}cats
    build:
      context: .
      dockerfile: Cats/Dockerfile
    depends_on:
        - mysql
    ports:
        - "55523:80"
    restart: always

  dogs:
    image: ${DOCKER_REGISTRY-}dogs
    build:
      context: .
      dockerfile: Dogs/Dockerfile
    depends_on:
        - postgresql
    ports:
        - "55524:80"
    restart: always