version: '3.4'

services:
  tanuljunk:
    image: ${DOCKER_REGISTRY-}tanuljunk
    build:
      context: .
      dockerfile: Tanuljunk/Dockerfile
    depends_on:
        - sql
        - postgresql
        - mysql
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
        - "1433:1433" 
    environment:
        - ACCEPT_EULA=y
        - SA_PASSWORD=A&VeryComplex123Password
  postgresql:
    image: "postgres:latest"
    container_name: postgresql
    environment:
        - POSTGRES_PASSWORD=A&VeryComplex123Password
    ports:
        - "5432:5432" 
  mysql: 
    image: "mysql:latest"
    container_name: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=A&VeryComplex123Password
    ports:
        - "3306:3306"   
    
