// <auto-generated />
using System;
using Dogs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dogs.Migrations
{
    [DbContext(typeof(DogContext))]
    [Migration("20231108143747_knowncats")]
    partial class knowncats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dogs.Models.Dog", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanDoTricks")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Key = new Guid("dc85ed44-3add-42b5-955b-41275ffcd51b"),
                            CanDoTricks = true,
                            Name = "okos kutya"
                        },
                        new
                        {
                            Key = new Guid("506bcdaa-6868-4eff-a54a-0877b74b095d"),
                            CanDoTricks = false,
                            Name = "buta kutya"
                        });
                });

            modelBuilder.Entity("Dogs.Models.KnownCat", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("KnownCats");
                });
#pragma warning restore 612, 618
        }
    }
}
