// <auto-generated />
using System;
using Dogs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dogs.Migrations
{
    [DbContext(typeof(DogContext))]
    partial class DogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dogs.Models.Dog", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanDoTricks")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Key = new Guid("97ef0ae2-5cad-47ab-b459-e834d5564e69"),
                            CanDoTricks = true,
                            Name = "okos kutya"
                        },
                        new
                        {
                            Key = new Guid("ce831456-b1ae-460a-beb8-5e8b95d72ba2"),
                            CanDoTricks = false,
                            Name = "buta kutya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
