//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
//using Tanuljunk.Data;

//#nullable disable

//namespace Tanuljunk.Migrations
//{
//    [DbContext(typeof(MainContext))]
//    [Migration("20230819194640_WeatherForecastsPostgres")]
//    partial class WeatherForecastsPostgres
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.10")
//                .HasAnnotation("Relational:MaxIdentifierLength", 63);

//            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

//            modelBuilder.Entity("Tanuljunk.Models.WeatherForecast", b =>
//                {
//                    b.Property<Guid>("Key")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("Summary")
//                        .HasColumnType("text");

//                    b.Property<int>("TemperatureC")
//                        .HasColumnType("integer");

//                    b.HasKey("Key");

//                    b.ToTable("WeatherForecasts");

//                    b.HasData(
//                        new
//                        {
//                            Key = new Guid("0b9dec5b-e60d-4737-93b6-e5540d6899ec"),
//                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddTicks(1234),
//                            Summary = "Meleg van",
//                            TemperatureC = 32
//                        },
//                        new
//                        {
//                            Key = new Guid("d70cddcb-c587-43ce-aaba-cd57aa894a17"),
//                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddTicks(5678),
//                            Summary = "Hideg van",
//                            TemperatureC = 3
//                        });
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
