//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Tanuljunk.Data;

//#nullable disable

//namespace Tanuljunk.Migrations
//{
//    [DbContext(typeof(MainContext))]
//    [Migration("20230819133245_WeatherForecasts")]
//    partial class WeatherForecasts
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.10")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Tanuljunk.Models.WeatherForecast", b =>
//                {
//                    b.Property<Guid>("Key")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Summary")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("TemperatureC")
//                        .HasColumnType("int");

//                    b.HasKey("Key");

//                    b.ToTable("WeatherForecasts");

//                    b.HasData(
//                        new
//                        {
//                            Key = new Guid("452288c4-a7c5-49f8-8068-5e7092339cff"),
//                            Date = new DateTime(2023, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
//                            Summary = "Meleg van",
//                            TemperatureC = 32
//                        },
//                        new
//                        {
//                            Key = new Guid("5e35f3cf-b27c-4a84-977c-6807af450939"),
//                            Date = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Local),
//                            Summary = "Hideg van",
//                            TemperatureC = 3
//                        });
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
