// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tanuljunk.Data;

#nullable disable

namespace Tanuljunk.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20230819194829_WeatherForecastsMysql")]
    partial class WeatherForecastsMysql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tanuljunk.Models.WeatherForecast", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Key = new Guid("1da85155-dd55-410d-b036-295f27320315"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddTicks(1234),
                            Summary = "Meleg van",
                            TemperatureC = 32
                        },
                        new
                        {
                            Key = new Guid("f2d23a88-5e5a-4144-9ffb-7ad7a10f1860"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddTicks(5678),
                            Summary = "Hideg van",
                            TemperatureC = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
