// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tanuljunk.Data;

#nullable disable

namespace Tanuljunk.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tanuljunk.Models.Weather", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Key = new Guid("9347081e-416a-4267-a1f3-9a54bfd8c557"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddTicks(1234),
                            Summary = "Meleg van",
                            TemperatureC = 32
                        },
                        new
                        {
                            Key = new Guid("311f3e98-f8a5-4675-9039-a7f76f369fb6"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddTicks(5678),
                            Summary = "Hideg van",
                            TemperatureC = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
