// <auto-generated />
using System;
using Cats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cats.Migrations
{
    [DbContext(typeof(CatContext))]
    [Migration("20230820060507_Cats")]
    partial class Cats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cats.Models.Cat", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Key = new Guid("29a6e1d3-59b8-41d3-a08a-c7e8b28c266d"),
                            Color = "orange",
                            Name = "very dumb cat"
                        },
                        new
                        {
                            Key = new Guid("a144b2b7-34b3-4530-b5da-448f3734f8ba"),
                            Color = "black",
                            Name = "smart cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
